
#资源服务器端口号
server:
  port: 8081
spring:
  application:
    name: oauth2-resource-server


#自定义jwt属性信息
jwt:
  type: jks # 密钥类型:secret，jks
  #  SECRET 是签名密钥，只生成一次即可，生成方法：
  #  Key key = Keys.secretKeyFor(SignatureAlgorithm.HS512);
  #  String secretString = Encoders.BASE64.encode(key.getEncoded()); # 使用 BASE64 编码
  secret: Ayl7bn+aFwxlakekKCJiqUYguKS80bEVb7OZtd2qfZjdCbAwKxDmM6PWezGy5JIkiJfemtHNPc7Av1l+OWQSqQ== # 秘钥
  #jks公钥文件
  publicKeyFile: oauth2_key.pub