server:
  port: 8086

#debug: true

spring:
  # 多个项目同时启动时，要修改这个端口，否则会因为端口冲突不能启动热部署，默认端口：35729
  devtools:
    livereload:
      port: 38006
  application:
    name: webflux-mysql-redis-demo

  #r2dbc mysql
  r2dbc:
#    url: r2dbc:mysql://mysql.test.db:3306/springboot?useUnicode=true&characterEncoding=utf-8
    # 开启代理，目的是打印sql，生产环境不建议，http://r2dbc.io/r2dbc-proxy/docs/current/docs/html/
    url: r2dbc:proxy:mysql://mysql.test.db:3306/springboot?useUnicode=true&characterEncoding=utf-8&proxyListener=com.example.r2dbc.LogExecutionListener
    username: testUser
    password: 123456
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  # redis 配置
  # springboot3.xx 配置: spring.data.redis，springboot2.xx 配置: spring.redis
  data:
    redis:
      database: 8
      host: redis.test.db  # Redis服务器地址
      password: password   # Redis服务器连接密码（默认为空）
      port: 6379           # Redis服务器连接端口
      timeout: 2000        # 连接空闲超过N(s秒、ms毫秒，不加单位默认毫秒)后关闭，0为禁用
      lettuce:             # 默认使用 lettuce 连接池
        pool:
          max-active: 20   # 允许最大连接数，默认8（负值表示没有限制）,通常为(cpu * 2) + 2
          max-idle: 10     # 最大空闲连接数，默认8
          min-idle: 5      # 最小空闲连接数，默认0
          max-wait: 2000   # 连接用完时，新的请求等待时间(s秒、ms毫秒，不加单位默认毫秒)，超过该时间抛出异常，(默认-1，负值表示没有限制)








# 可以打印sql，但不能打印参数值
logging:
  level:
#    io.r2dbc.pool: DEBUG
#    io.asyncer.r2dbc.mysql: DEBUG
    org.springframework.r2dbc: DEBUG
    com.hanqunfeng.reactive.redis.cache: DEBUG


