
#资源服务器端口号
server:
  port: 8082
spring:
  application:
    name: oauth2-resource-server2

  #oauth2 配置
  security:
    oauth2:
      resourceserver:
        jwt:
          # 公钥文件路径
          # public-key-location: classpath:oauth2_key.pub

          # 认证服务器提供的密钥验证路径
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

