

#\u8D44\u6E90\u670D\u52A1\u5668\u7AEF\u53E3\u53F7
server:
  port: 8099
  servlet:


oauth2:
  server:
    url: http://localhost:8080
    logout: ${oauth2.server.url}/logout #\u53EF\u4EE5\u5B9E\u73B0\u5355\u70B9\u767B\u5F55\uFF0C\u4E0D\u80FD\u5B9E\u73B0\u5355\u70B9\u767B\u51FA


spring:
  application:
    name: oauth2-client-webflux
  #资源国际化
  messages:
    basename: static/i18n/messages
    encoding: utf-8

  #thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html


  #\u6570\u636E\u6E90\u914D\u7F6E
  #r2dbc mysql
#  r2dbc:
#    url: r2dbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
#    username: root
#    password: newpwd
#    pool:
#      enabled: true
#      initial-size: 5
#      max-size: 20
#      max-idle-time: 30m



  #oauth2\u5BA2\u6237\u7AEF\u914D\u7F6E\uFF0C\u9ED8\u8BA4\u57FA\u4E8E\u5185\u5B58\uFF0C\u5982\u679C\u57FA\u4E8E\u6570\u636E\u5E93\uFF0C\u9700\u8981\u5728config\u914D\u7F6E\u7C7B\u4E2D\u8FDB\u884C\u76F8\u5E94\u7684\u914D\u7F6E
  security:
    oauth2:
      client:
        registration: #\u652F\u6301\u591A\u79DF\u6237
          # /oauth2/authorization/flux-client # \u9700\u8981\u5148\u8BBF\u95EE\u8FD9\u4E2A\u5730\u5740\u8FDB\u884C\u8BA4\u8BC1
          flux-client: # 1 \u6CE8\u518C\u5BA2\u6237\u7AEF\u540D\u79F0\uFF0C\u968F\u610F\u6307\u5B9A\uFF0C\u4F46\u662F\u8981\u4E0Eprovider\u7684\u914D\u7F6E\u76F8\u4E00\u81F4
            client-id: postman # 2 \u5BA2\u6237\u7AEFID
            client-secret: postman # 3 \u5BA2\u6237\u7AEF\u5BC6\u7801
            authorization-grant-type: authorization_code # 4 \u8BA4\u8BC1\u7C7B\u578B
            #\u9ED8\u8BA4\u91CD\u5B9A\u5411URI\u6A21\u677F\u662F/login/oauth2/code/{registrationId}\u3002
            #registrationId\u662FClientRegistration\u7684\u552F\u4E00\u6807\u8BC6\u7B26\u3002
            redirect-uri: http://localhost:8099/login/oauth2/code/flux-client  # 5 \u56DE\u8C03\u5730\u5740\uFF0C\u9700\u8981\u914D\u7F6E\u5230\u6570\u636E\u8868\u4E2D\uFF0C\u9ED8\u8BA4\u5199\u6CD5\uFF0C\u6CE8\u610F\u6700\u540E\u7684\u8DEF\u5F84\u662F\u6CE8\u518C\u5BA2\u6237\u7AEF\u540D\u79F0
            scope: any #\u8BF7\u6C42\u8303\u56F4
            client-name: 客户端1
#          # /oauth2/authorization/flux-client2
          flux-client2: # 1 \u6CE8\u518C\u5BA2\u6237\u7AEF\u540D\u79F0\uFF0C\u968F\u610F\u6307\u5B9A\uFF0C\u4F46\u662F\u8981\u4E0Eprovider\u7684\u914D\u7F6E\u76F8\u4E00\u81F4
            client-id: postman # 2 \u5BA2\u6237\u7AEFID
            client-secret: postman # 3 \u5BA2\u6237\u7AEF\u5BC6\u7801
            authorization-grant-type: authorization_code # 4 \u8BA4\u8BC1\u7C7B\u578B
            redirect-uri: http://localhost:8099/login/oauth2/code/flux-client2  # 5 \u56DE\u8C03\u5730\u5740\uFF0C\u9700\u8981\u914D\u7F6E\u5230\u6570\u636E\u8868\u4E2D\uFF0C\u9ED8\u8BA4\u5199\u6CD5\uFF0C\u6CE8\u610F\u6700\u540E\u7684\u8DEF\u5F84\u662F\u6CE8\u518C\u5BA2\u6237\u7AEF\u540D\u79F0
            scope: any #\u8BF7\u6C42\u8303\u56F4
            client-name: 客户端2

          # CommonOAuth2Provider \u4E2D\u5B9A\u4E49\u4E86google,facebook,github,okta\u7684\u9ED8\u8BA4provider\u4FE1\u606F\uFF0C\u6240\u4EE5\u8FD9\u91CC\u4E0D\u9700\u8981\u4E3A\u5176\u914D\u7F6Eprovider\u4FE1\u606F
          # /oauth2/authorization/google
          # \u91CD\u5B9A\u5411\u540E\uFF1Ahttps://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=xxxxxxxxx&scope=openid%20profile%20email&state=jO3PpuX2IzwOFemdd7FHBIHeeSPcxDwiP-mqDBTjdfw%3D&redirect_uri=http://localhost:8088/postman/login/oauth2/code/google&nonce=-sxhj2hjgrc7krSHSjL3qz_W90xPEX9nlP6SYzAfktY
          google: # google\u5E10\u53F7\u8BA4\u8BC1\uFF0C\u8DF3\u8F6C\u5230google\u767B\u5F55\u9875\u9762
            client-id: xxxxxxxxx #  \u5BA2\u6237\u7AEFID
            client-secret: xxxxxxx #  \u5BA2\u6237\u7AEF\u5BC6\u7801
            client-name: Google认证

          # /oauth2/authorization/facebook
          # https://www.facebook.com/v2.8/dialog/oauth?response_type=code&client_id=xxxxxxxxx&scope=public_profile%20email&state=BVZM3OW2EUS82pbjJdpQfXvtXbFbMwaUe_lRMOt4BW4%3D&redirect_uri=http://localhost:8088/postman/login/oauth2/code/facebook
          facebook: # facebook\u5E10\u53F7\u767B\u5F55\uFF0C\u8DF3\u8F6C\u5230facebook\u767B\u5F55\u9875\u9762
            client-id: xxxxxxxxx #  \u5BA2\u6237\u7AEFID
            client-secret: xxxxxxx #  \u5BA2\u6237\u7AEF\u5BC6\u7801
            client-name: Facebook认证

          # /oauth2/authorization/github
          # \u91CD\u5B9A\u5411\u540E\uFF1Ahttps://github.com/login?client_id=xxxxxxxxx&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3Dxxxxxxxxx%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8088%252Fpostman%252Flogin%252Foauth2%252Fcode%252Fgithub%26response_type%3Dcode%26scope%3Dread%253Auser%26state%3DmXtRWMQy8NaqVsFiie-NyYuy2z8OErrdq_VsuejDOPE%253D
          # api\u6587\u6863\uFF1Ahttps://docs.github.com/cn/free-pro-team@latest/rest
          github: # github\u5E10\u53F7\u767B\u5F55\uFF0C\u8DF3\u8F6C\u5230github\u767B\u5F55\u9875\u9762
            client-id: xxxxxxxxx #  \u5BA2\u6237\u7AEFID
            client-secret: xxxxxxx #  \u5BA2\u6237\u7AEF\u5BC6\u7801
            client-name: Github认证

        provider:
          flux-client: # 6 \u6CE8\u518C\u5BA2\u6237\u7AEF\u540D\u79F0
            authorization-uri: ${oauth2.server.url}/oauth/authorize # 7 \u8BA4\u8BC1\u5730\u5740
            token-uri: ${oauth2.server.url}/oauth/token # 8 \u83B7\u53D6token\u5730\u5740
            user-info-uri: http://localhost:8080/userInfo # 9 \u83B7\u53D6\u7528\u6237\u4FE1\u606F\u5730\u5740\uFF0C\u5FC5\u987B\u914D\u7F6E
            userNameAttribute: username # 10 \u6307\u5B9A\u7528\u6237\u4FE1\u606F\u4E2D\u54EA\u4E2A\u5C5E\u6027\u662F\u7528\u6237\u540D\u79F0
          flux-client2: # 6 \u6CE8\u518C\u5BA2\u6237\u7AEF\u540D\u79F0
            authorization-uri: ${oauth2.server.url}/oauth/authorize # 7 \u8BA4\u8BC1\u5730\u5740
            token-uri: ${oauth2.server.url}/oauth/token # 8 \u83B7\u53D6token\u5730\u5740
            user-info-uri: http://localhost:8080/userInfo # 9 \u83B7\u53D6\u7528\u6237\u4FE1\u606F\u5730\u5740\uFF0C\u5FC5\u987B\u914D\u7F6E
            userNameAttribute: username # 10 \u6307\u5B9A\u7528\u6237\u4FE1\u606F\u4E2D\u54EA\u4E2A\u5C5E\u6027\u662F\u7528\u6237\u540D\u79F0
debug: true
