

server:
  port: 8891
  servlet:
    session:
      timeout: 10s
      cookie:
        http-only: true
        secure: false

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: jwt-resources-webflux-server

  #r2dbc mysql
  r2dbc:
    url: r2dbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: newpwd
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  #配置redis连接
  redis:
    host: 127.0.0.1
    #默认端口：6379
    port: 6379
    password: password
    #默认的0号库
    database: 1
    #连接超时时间，单位毫秒
    timeout: 1000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5
        #获取连接池最大等待时间，单位毫秒
        max-wait: 2000


# 可以打印sql
logging:
  level:
    org.springframework.data.r2dbc: DEBUG

jwt:
  # jks,rsa,secret,默认secret
  type: jks
  #  SECRET
  #  Key key = Keys.secretKeyFor(SignatureAlgorithm.HS512);
  #  String secretString = Encoders.BASE64.encode(key.getEncoded());
  secret: Ayl7bn+aFwxlakekKCJiqUYguKS80bEVb7OZtd2qfZjdCbAwKxDmM6PWezGy5JIkiJfemtHNPc7Av1l+OWQSqQ==
  expiration: 3600000   # token过期时间
  header: JWTHeaderName # header属性名称
  # rsa
  rsaPubKeyFile: classpath:id_key_rsa.pub
  # jks
  jksPubKeyFile: classpath:oauth2_key.pub


#springsecurity 自定义属性
security:
  permitAll:
    - /login*
  ignoring:
    - '**/*.js'
    - '**/*.css'
    - /static/**



# 开启debug
debug: false