
#资源服务器端口号
server:
  port: 8088
  servlet:
    #不能配置为/，否则不能认证通过后不能重定向回客户端的访问地址
    #本机回调地址为http://localhost:8088/postman/login，需要配置到认证服务器客户端对应的redirectUris中
    context-path: /postman


oauth2:
  server:
    url: http://localhost:8080
    logout: ${oauth2.server.url}/logout #可以实现单点登录，不能实现单点登出


spring:
  application:
    name: oauth2-client-postman2

  #数据源配置
  datasource:
    #    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    url: jdbc:p6spy:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: newpwd
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connection-timeout: 30000 #毫秒，默认30秒
      idle-timeout: 600000      #毫秒，默认10分钟
      max-lifetime: 1800000     #毫秒，默认30分钟
      maximum-pool-size: 10     #默认10

  #oauth2客户端配置，默认基于内存，如果基于数据库，需要在config配置类中加入
  security:
    oauth2:
      client:
        registration:
          my-client: # 1 注册客户端名称，随意指定，但是要与provider的配置相一致
            client-id: postman # 2 客户端ID
            client-secret: postman # 3 客户端密码
            authorization-grant-type: authorization_code # 4 认证类型
            redirect-uri: http://localhost:8088/postman/login/oauth2/code/my-client  # 5 回调地址，需要配置到数据表中，注意最后的路径是注册客户端名称
            scope: any #请求范围

        provider:
          my-client: # 6 注册客户端名称
            authorization-uri: ${oauth2.server.url}/oauth/authorize # 7 认证地址
            token-uri: ${oauth2.server.url}/oauth/token # 8 获取token地址
            user-info-uri: http://localhost:8080/userInfo # 9 获取用户信息地址，必须配置，切该地址可用
            userNameAttribute: username # 10 指定用户信息中哪个属性是用户名称


