#认证服务器端口号
server:
  port: 8080
spring:
  application:
    name: oauth2-auth-server


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #数据源配置
  datasource:
#    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    url: jdbc:p6spy:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: newpwd
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connection-timeout: 30000 #毫秒，默认30秒
      idle-timeout: 600000      #毫秒，默认10分钟
      max-lifetime: 1800000     #毫秒，默认30分钟
      maximum-pool-size: 10     #默认10

  #资源国际化
  messages:
    basename: static/i18n/messages
    encoding: utf-8

  #thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html

  #oauth2 配置
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:oauth2_key.pub


#springsecurity 自定义属性
security:
  #不需要验证的路径
  permitAll:
    - /redirect/**
  ignoring:
    - /webjars/**
    - /**/*.js
    - /**/*.css
    - /static/**

#自定义jwt属性信息
jwt:
  type: jks # 密钥类型：secret，jks
  #  SECRET 是签名密钥，只生成一次即可，生成方法：
  #  Key key = Keys.secretKeyFor(SignatureAlgorithm.HS512);
  #  String secretString = Encoders.BASE64.encode(key.getEncoded()); # 使用 BASE64 编码
  secret: Ayl7bn+aFwxlakekKCJiqUYguKS80bEVb7OZtd2qfZjdCbAwKxDmM6PWezGy5JIkiJfemtHNPc7Av1l+OWQSqQ== # 秘钥
  accessTokenValiditySeconds: 43200   # access_token过期时间 (秒) ,默认值12小时
  refreshTokenValiditySeconds: 2592000 # refresh_token过期时间 (秒) ,默认值30天
  jksKeyFile: classpath:oauth2_key.jks
  jksStorePassword: 123456
  jksKeyAlias: oauth2
  jksKeyPassword: 123456


#oauth2的client信息是基于内存还是基于数据库，如果不配置，默认为基于内存
oauth2:
  clients:
    config:
      jdbc: true


